In [ ]:
!pip install tensorflow pandas numpy

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [ ]:
df = pd.read_csv("/content/car details v4.csv")

In [ ]:
df.head(10)

,Make,Model,Price,Year,Kilometer,Fuel Type,Transmission,Location,Color,Owner,Seller Type,Engine,Max Power,Max Torque,Drivetrain,Length,Width,Height,Seating Capacity,Fuel Tank Capacity
0,Honda,Amaze 1.2 VX i-VTEC,505000,2017,87150,Petrol,Manual,Pune,Grey,First,Corporate,1198 cc,87 bhp @ 6000 rpm,109 Nm @ 4500 rpm,FWD,3990.0,1680.0,1505.0,5.0,35.0
1,Maruti Suzuki,Swift DZire VDI,450000,2014,75000,Diesel,Manual,Ludhiana,White,Second,Individual,1248 cc,74 bhp @ 4000 rpm,190 Nm @ 2000 rpm,FWD,3995.0,1695.0,1555.0,5.0,42.0
2,Hyundai,i10 Magna 1.2 Kappa2,220000,2011,67000,Petrol,Manual,Lucknow,Maroon,First,Individual,1197 cc,79 bhp @ 6000 rpm,112.7619 Nm @ 4000 rpm,FWD,3585.0,1595.0,1550.0,5.0,35.0
3,Toyota,Glanza G,799000,2019,37500,Petrol,Manual,Mangalore,Red,First,Individual,1197 cc,82 bhp @ 6000 rpm,113 Nm @ 4200 rpm,FWD,3995.0,1745.0,1510.0,5.0,37.0
4,Toyota,Innova 2.4 VX 7 STR [2016-2020],1950000,2018,69000,Diesel,Manual,Mumbai,Grey,First,Individual,2393 cc,148 bhp @ 3400 rpm,343 Nm @ 1400 rpm,RWD,4735.0,1830.0,1795.0,7.0,55.0
5,Maruti Suzuki,Ciaz ZXi,675000,2017,73315,Petrol,Manual,Pune,Grey,First,Individual,1373 cc,91 bhp @ 6000 rpm,130 Nm @ 4000 rpm,FWD,4490.0,1730.0,1485.0,5.0,43.0
6,Mercedes-Benz,CLA 200 Petrol Sport,1898999,2015,47000,Petrol,Automatic,Mumbai,White,Second,Individual,1991 cc,181 bhp @ 5500 rpm,300 Nm @ 1200 rpm,FWD,4630.0,1777.0,1432.0,5.0,NaN
7,BMW,X1 xDrive20d M Sport,2650000,2017,75000,Diesel,Automatic,Coimbatore,White,Second,Individual,1995 cc,188 bhp @ 4000 rpm,400 Nm @ 1750 rpm,AWD,4439.0,1821.0,1612.0,5.0,51.0
8,Skoda,Octavia 1.8 TSI Style Plus AT [2017],1390000,2017,56000,Petrol,Automatic,Mumbai,White,First,Individual,1798 cc,177 bhp @ 5100 rpm,250 Nm @ 1250 rpm,FWD,4670.0,1814.0,1476.0,5.0,50.0
9,Nissan,Terrano XL (D),575000,2015,85000,Diesel,Manual,Mumbai,White,First,Individual,1461 cc,84 bhp @ 3750 rpm,200 Nm @ 1900 rpm,FWD,4331.0,1822.0,1671.0,5.0,50.0

## preprocessing

In [ ]:
int_columns = df.select_dtypes(include="int64").columns.values
object_columns = df.select_dtypes(include="object").columns.values
float_columns = df.select_dtypes(include="float64").columns.values

print(int_columns)
print(object_columns)
print(float_columns)

['Price' 'Year' 'Kilometer']
['Make' 'Model' 'Fuel Type' 'Transmission' 'Location' 'Color' 'Owner'
 'Seller Type' 'Engine' 'Max Power' 'Max Torque' 'Drivetrain']
['Length' 'Width' 'Height' 'Seating Capacity' 'Fuel Tank Capacity']

In [ ]:
df_droped.head(10)

,Price,Year,Kilometer,Transmission,Owner,Engine,Max Power,Max Torque,Drivetrain,Length,Width,Height,Seating Capacity,Fuel Tank Capacity
0,505000,2017,87150,1,0,1198.0,87.0,109.0,0.0,3990.0,1680.0,1505.0,5.0,35.000000
2,220000,2011,67000,1,0,1197.0,79.0,112.0,0.0,3585.0,1595.0,1550.0,5.0,35.000000
3,799000,2019,37500,1,0,1197.0,82.0,113.0,0.0,3995.0,1745.0,1510.0,5.0,37.000000
4,1950000,2018,69000,1,0,2393.0,148.0,343.0,1.0,4735.0,1830.0,1795.0,7.0,55.000000
5,675000,2017,73315,1,0,1373.0,91.0,130.0,0.0,4490.0,1730.0,1485.0,5.0,43.000000
6,1898999,2015,47000,0,1,1991.0,181.0,300.0,0.0,4630.0,1777.0,1432.0,5.0,52.007352
7,2650000,2017,75000,0,1,1995.0,188.0,400.0,2.0,4439.0,1821.0,1612.0,5.0,51.000000
8,1390000,2017,56000,0,0,1798.0,177.0,250.0,0.0,4670.0,1814.0,1476.0,5.0,50.000000
9,575000,2015,85000,1,0,1461.0,84.0,200.0,0.0,4331.0,1822.0,1671.0,5.0,50.000000
10,591000,2017,20281,1,0,1197.0,82.0,115.0,0.0,3985.0,1734.0,1505.0,5.0,45.000000

In [ ]:
df_droped = df.drop(columns = ["Model" , "Fuel Type" , "Location" , "Color" , "Seller Type" , "Make"] , index=1)

In [ ]:
import re

def extract_number(value):

  # print(value)
  pattern = r"(\d+)"
  if isinstance(value , str):
    match = re.search(pattern, value)
    if match:
        number_before_bhp = int(match.group(1))
        return number_before_bhp

df_droped["Max Power"] = df_droped["Max Power"].apply(extract_number)
df_droped["Max Torque"] = df_droped["Max Torque"].apply(extract_number)
df_droped["Engine"] = df_droped["Engine"].apply(extract_number)

In [ ]:
df_droped["Drivetrain"].value_counts()

FWD    1329
RWD     321
AWD     272
Name: Drivetrain, dtype: int64

In [ ]:
df_droped["Transmission"] = df_droped["Transmission"].replace(["Automatic" , "Manual"] , [0 , 1])
df_droped["Owner"] = df_droped["Owner"].replace(["First" , "Second" , "Third" , "UnRegistered Car" , "Fourth" , "4 or More"] , [0 , 1 , 2, 3, 4 , 5])
df_droped["Drivetrain"] = df_droped["Drivetrain"].replace(["FWD" , "RWD" , "AWD"] , [0 , 1 , 2])

In [ ]:
df_droped.isna().sum()

Price                 0
Year                  0
Kilometer             0
Transmission          0
Owner                 0
Engine                0
Max Power             0
Max Torque            0
Drivetrain            0
Length                0
Width                 0
Height                0
Seating Capacity      0
Fuel Tank Capacity    0
dtype: int64

In [ ]:
# List of columns for which you want to fill missing values with the mode
cat_columns_to_fill = ['Drivetrain', 'Seating Capacity']

# Fill missing values with the mode for the specified columns
for column in cat_columns_to_fill:
    df_droped[column] = df_droped[column].fillna(df_droped[column].mode().iloc[0])

num_columns_to_fill = ['Engine', 'Max Torque' , 'Max Power' , 'Length' , 'Width' , 'Height' , 'Fuel Tank Capacity']

# Fill missing values with the mode for the specified columns
for column in num_columns_to_fill:
    df_droped[column] = df_droped[column].fillna(df_droped[column].mean())

In [ ]:
df_droped.to_csv("/content/output.csv" , index = False)

In [ ]:
df_droped = pd.read_csv("/content/output.csv")

In [ ]:
df_droped.head(10)

,Price,Year,Kilometer,Transmission,Owner,Engine,Max Power,Max Torque,Drivetrain,Length,Width,Height,Seating Capacity,Fuel Tank Capacity
0,505000,2017,87150,1,0,1198.0,87.0,109.0,0.0,3990.0,1680.0,1505.0,5.0,35.000000
1,220000,2011,67000,1,0,1197.0,79.0,112.0,0.0,3585.0,1595.0,1550.0,5.0,35.000000
2,799000,2019,37500,1,0,1197.0,82.0,113.0,0.0,3995.0,1745.0,1510.0,5.0,37.000000
3,1950000,2018,69000,1,0,2393.0,148.0,343.0,1.0,4735.0,1830.0,1795.0,7.0,55.000000
4,675000,2017,73315,1,0,1373.0,91.0,130.0,0.0,4490.0,1730.0,1485.0,5.0,43.000000
5,1898999,2015,47000,0,1,1991.0,181.0,300.0,0.0,4630.0,1777.0,1432.0,5.0,52.007352
6,2650000,2017,75000,0,1,1995.0,188.0,400.0,2.0,4439.0,1821.0,1612.0,5.0,51.000000
7,1390000,2017,56000,0,0,1798.0,177.0,250.0,0.0,4670.0,1814.0,1476.0,5.0,50.000000
8,575000,2015,85000,1,0,1461.0,84.0,200.0,0.0,4331.0,1822.0,1671.0,5.0,50.000000
9,591000,2017,20281,1,0,1197.0,82.0,115.0,0.0,3985.0,1734.0,1505.0,5.0,45.000000

In [ ]:
cat_columns = ["Transmission" , "Owner" , "Drivetrain" , "Seating Capacity"]

df_one_hot = pd.get_dummies(df_droped , columns = cat_columns)

In [ ]:
num_columns = df_one_hot.select_dtypes(["int" , "float"]).columns.values.tolist()
num_columns.remove("Price")

In [ ]:
num_columns

['Year',
 'Kilometer',
 'Engine',
 'Max Power',
 'Max Torque',
 'Length',
 'Width',
 'Height',
 'Fuel Tank Capacity']

In [ ]:
scaler = StandardScaler()

df_one_hot[num_columns] = scaler.fit_transform(df_one_hot[num_columns])
df_scaled = df_one_hot

In [ ]:
df_scaled.head(10)

,Price,Year,Kilometer,Engine,Max Power,Max Torque,Length,Width,Height,Fuel Tank Capacity,...,Owner_5,Drivetrain_0.0,Drivetrain_1.0,Drivetrain_2.0,Seating Capacity_2.0,Seating Capacity_4.0,Seating Capacity_5.0,Seating Capacity_6.0,Seating Capacity_7.0,Seating Capacity_8.0
0,505000,0.170487,0.574188,-0.784122,-0.668488,-0.993890,-0.668239,-0.661192,-0.647711,-1.157920e+00,...,0,1,0,0,0,0,1,0,0,0
1,220000,-1.613561,0.222898,-0.785707,-0.793910,-0.972105,-1.598250,-1.299636,-0.311737,-1.157920e+00,...,0,1,0,0,0,0,1,0,0,0
2,799000,0.765170,-0.291399,-0.785707,-0.746877,-0.964844,-0.656758,-0.172970,-0.610381,-1.021753e+00,...,0,1,0,0,0,0,1,0,0,0
3,1950000,0.467829,0.257765,1.109624,0.287849,0.705321,1.042522,0.465474,1.517454,2.037498e-01,...,0,0,1,0,0,0,0,0,1,0
4,675000,0.170487,0.332992,-0.506796,-0.605778,-0.841397,0.479922,-0.285637,-0.797033,-6.132518e-01,...,0,1,0,0,0,0,1,0,0,0
5,1898999,-0.424195,-0.125778,0.472565,0.805212,0.393073,0.801408,0.067385,-1.192735,4.837622e-16,...,0,1,0,0,0,0,1,0,0,0
6,2650000,0.170487,0.362368,0.478903,0.914956,1.119231,0.362810,0.397874,0.151160,-6.858403e-02,...,0,0,0,1,0,0,1,0,0,0
7,1390000,0.170487,0.031126,0.166713,0.742501,0.029994,0.893261,0.345296,-0.864228,-1.366675e-01,...,0,1,0,0,0,0,1,0,0,0
8,575000,-0.424195,0.536706,-0.367340,-0.715521,-0.333086,0.114807,0.405385,0.591659,-1.366675e-01,...,0,1,0,0,0,0,1,0,0,0
9,591000,0.170487,-0.591591,-0.785707,-0.746877,-0.950321,-0.679721,-0.255592,-0.647711,-4.770849e-01,...,0,1,0,0,0,0,1,0,0,0

In [ ]:
df_scaled["Price"] = df_scaled["Price"].apply(lambda x : x/1000000)

In [ ]:
train_columns = df_scaled.columns.values.tolist()
train_columns.remove("Price")
# print(columns)
X = df_scaled[train_columns]
y = df_scaled["Price"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [ ]:
y_train

266     0.950
1133    1.251
1823    0.660
1370    1.650
67      0.190
        ...
1638    0.650
1095    3.250
1130    1.090
1294    3.090
860     4.200
Name: Price, Length: 1646, dtype: float64

In [ ]:
from tensorflow.keras.metrics import MeanSquaredError, MeanAbsoluteError, RootMeanSquaredError

# Step 4: Build the TensorFlow Regression Model
model = tf.keras.Sequential([
    tf.keras.layers.Dense(128, activation='relu', input_shape=(X_train.shape[1],)),
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dense(32, activation='relu'),
    tf.keras.layers.Dense(1)  # Single output neuron for regression
])

# Step 5: Compile the Model
model.compile(optimizer='adam', loss='mean_squared_error' , metrics=[MeanSquaredError() , MeanAbsoluteError() , RootMeanSquaredError()])

# Step 6: Train the Model
num_epochs = 100
batch_size = 32
model.fit(X_train, y_train, epochs=num_epochs, batch_size=batch_size, validation_data=(X_test, y_test))

Epoch 1/100
52/52 [==============================] - 2s 9ms/step - loss: 3.6156 - mean_squared_error: 3.6156 - mean_absolute_error: 0.9547 - root_mean_squared_error: 1.9015 - val_loss: 2.5270 - val_mean_squared_error: 2.5270 - val_mean_absolute_error: 0.6611 - val_root_mean_squared_error: 1.5896
Epoch 2/100
52/52 [==============================] - 0s 4ms/step - loss: 1.2518 - mean_squared_error: 1.2518 - mean_absolute_error: 0.4662 - root_mean_squared_error: 1.1188 - val_loss: 1.7994 - val_mean_squared_error: 1.7994 - val_mean_absolute_error: 0.4762 - val_root_mean_squared_error: 1.3414
Epoch 3/100
52/52 [==============================] - 0s 4ms/step - loss: 1.0494 - mean_squared_error: 1.0494 - mean_absolute_error: 0.4172 - root_mean_squared_error: 1.0244 - val_loss: 1.5408 - val_mean_squared_error: 1.5408 - val_mean_absolute_error: 0.4718 - val_root_mean_squared_error: 1.2413
Epoch 4/100
52/52 [==============================] - 0s 5ms/step - loss: 0.8894 - mean_squared_error: 0.8894 - mean_absolute_error: 0.3954 - root_mean_squared_error: 0.9431 - val_loss: 1.4399 - val_mean_squared_error: 1.4399 - val_mean_absolute_error: 0.4535 - val_root_mean_squared_error: 1.2000
Epoch 5/100
52/52 [==============================] - 0s 4ms/step - loss: 0.8781 - mean_squared_error: 0.8781 - mean_absolute_error: 0.3935 - root_mean_squared_error: 0.9371 - val_loss: 1.4489 - val_mean_squared_error: 1.4489 - val_mean_absolute_error: 0.4090 - val_root_mean_squared_error: 1.2037
Epoch 6/100
52/52 [==============================] - 0s 4ms/step - loss: 0.7562 - mean_squared_error: 0.7562 - mean_absolute_error: 0.3832 - root_mean_squared_error: 0.8696 - val_loss: 1.3500 - val_mean_squared_error: 1.3500 - val_mean_absolute_error: 0.4443 - val_root_mean_squared_error: 1.1619
Epoch 7/100
52/52 [==============================] - 0s 4ms/step - loss: 0.8761 - mean_squared_error: 0.8761 - mean_absolute_error: 0.4184 - root_mean_squared_error: 0.9360 - val_loss: 1.4907 - val_mean_squared_error: 1.4907 - val_mean_absolute_error: 0.4393 - val_root_mean_squared_error: 1.2209
Epoch 8/100
52/52 [==============================] - 0s 4ms/step - loss: 0.7510 - mean_squared_error: 0.7510 - mean_absolute_error: 0.3908 - root_mean_squared_error: 0.8666 - val_loss: 1.5792 - val_mean_squared_error: 1.5792 - val_mean_absolute_error: 0.4373 - val_root_mean_squared_error: 1.2567
Epoch 9/100
52/52 [==============================] - 0s 5ms/step - loss: 0.6318 - mean_squared_error: 0.6318 - mean_absolute_error: 0.3474 - root_mean_squared_error: 0.7949 - val_loss: 1.1388 - val_mean_squared_error: 1.1388 - val_mean_absolute_error: 0.4054 - val_root_mean_squared_error: 1.0672
Epoch 10/100
52/52 [==============================] - 0s 5ms/step - loss: 0.7682 - mean_squared_error: 0.7682 - mean_absolute_error: 0.4101 - root_mean_squared_error: 0.8765 - val_loss: 1.1365 - val_mean_squared_error: 1.1365 - val_mean_absolute_error: 0.5034 - val_root_mean_squared_error: 1.0661
Epoch 11/100
52/52 [==============================] - 0s 4ms/step - loss: 0.6363 - mean_squared_error: 0.6363 - mean_absolute_error: 0.3709 - root_mean_squared_error: 0.7977 - val_loss: 0.8870 - val_mean_squared_error: 0.8870 - val_mean_absolute_error: 0.4689 - val_root_mean_squared_error: 0.9418
Epoch 12/100
52/52 [==============================] - 0s 5ms/step - loss: 0.5343 - mean_squared_error: 0.5343 - mean_absolute_error: 0.3362 - root_mean_squared_error: 0.7310 - val_loss: 0.8394 - val_mean_squared_error: 0.8394 - val_mean_absolute_error: 0.3838 - val_root_mean_squared_error: 0.9162
Epoch 13/100
52/52 [==============================] - 0s 5ms/step - loss: 0.4771 - mean_squared_error: 0.4771 - mean_absolute_error: 0.3214 - root_mean_squared_error: 0.6907 - val_loss: 0.8942 - val_mean_squared_error: 0.8942 - val_mean_absolute_error: 0.3758 - val_root_mean_squared_error: 0.9456
Epoch 14/100
52/52 [==============================] - 0s 5ms/step - loss: 0.4356 - mean_squared_error: 0.4356 - mean_absolute_error: 0.3113 - root_mean_squared_error: 0.6600 - val_loss: 0.8255 - val_mean_squared_error: 0.8255 - val_mean_absolute_error: 0.3657 - val_root_mean_squared_error: 0.9086
Epoch 15/100
52/52 [==============================] - 0s 5ms/step - loss: 0.3994 - mean_squared_error: 0.3994 - mean_absolute_error: 0.3101 - root_mean_squared_error: 0.6320 - val_loss: 0.7160 - val_mean_squared_error: 0.7160 - val_mean_absolute_error: 0.4113 - val_root_mean_squared_error: 0.8462
Epoch 16/100
52/52 [==============================] - 0s 5ms/step - loss: 0.4035 - mean_squared_error: 0.4035 - mean_absolute_error: 0.3097 - root_mean_squared_error: 0.6352 - val_loss: 0.9925 - val_mean_squared_error: 0.9925 - val_mean_absolute_error: 0.4047 - val_root_mean_squared_error: 0.9962
Epoch 17/100
52/52 [==============================] - 0s 5ms/step - loss: 0.4265 - mean_squared_error: 0.4265 - mean_absolute_error: 0.3451 - root_mean_squared_error: 0.6531 - val_loss: 0.7660 - val_mean_squared_error: 0.7660 - val_mean_absolute_error: 0.3986 - val_root_mean_squared_error: 0.8752
Epoch 18/100
52/52 [==============================] - 0s 5ms/step - loss: 0.3638 - mean_squared_error: 0.3638 - mean_absolute_error: 0.2908 - root_mean_squared_error: 0.6031 - val_loss: 0.8739 - val_mean_squared_error: 0.8739 - val_mean_absolute_error: 0.3543 - val_root_mean_squared_error: 0.9348
Epoch 19/100
52/52 [==============================] - 0s 4ms/step - loss: 0.3025 - mean_squared_error: 0.3025 - mean_absolute_error: 0.2773 - root_mean_squared_error: 0.5500 - val_loss: 0.6430 - val_mean_squared_error: 0.6430 - val_mean_absolute_error: 0.3318 - val_root_mean_squared_error: 0.8019
Epoch 20/100
52/52 [==============================] - 0s 5ms/step - loss: 0.2717 - mean_squared_error: 0.2717 - mean_absolute_error: 0.2716 - root_mean_squared_error: 0.5212 - val_loss: 0.6706 - val_mean_squared_error: 0.6706 - val_mean_absolute_error: 0.3322 - val_root_mean_squared_error: 0.8189
Epoch 21/100
52/52 [==============================] - 0s 4ms/step - loss: 0.2746 - mean_squared_error: 0.2746 - mean_absolute_error: 0.2697 - root_mean_squared_error: 0.5240 - val_loss: 0.9990 - val_mean_squared_error: 0.9990 - val_mean_absolute_error: 0.3702 - val_root_mean_squared_error: 0.9995
Epoch 22/100
52/52 [==============================] - 0s 4ms/step - loss: 0.2443 - mean_squared_error: 0.2443 - mean_absolute_error: 0.2597 - root_mean_squared_error: 0.4943 - val_loss: 0.7309 - val_mean_squared_error: 0.7309 - val_mean_absolute_error: 0.3434 - val_root_mean_squared_error: 0.8549
Epoch 23/100
52/52 [==============================] - 0s 4ms/step - loss: 0.2326 - mean_squared_error: 0.2326 - mean_absolute_error: 0.2496 - root_mean_squared_error: 0.4822 - val_loss: 0.7436 - val_mean_squared_error: 0.7436 - val_mean_absolute_error: 0.3371 - val_root_mean_squared_error: 0.8623
Epoch 24/100
52/52 [==============================] - 0s 5ms/step - loss: 0.2204 - mean_squared_error: 0.2204 - mean_absolute_error: 0.2417 - root_mean_squared_error: 0.4695 - val_loss: 0.9377 - val_mean_squared_error: 0.9377 - val_mean_absolute_error: 0.3603 - val_root_mean_squared_error: 0.9683
Epoch 25/100
52/52 [==============================] - 0s 5ms/step - loss: 0.2136 - mean_squared_error: 0.2136 - mean_absolute_error: 0.2429 - root_mean_squared_error: 0.4622 - val_loss: 0.7098 - val_mean_squared_error: 0.7098 - val_mean_absolute_error: 0.3285 - val_root_mean_squared_error: 0.8425
Epoch 26/100
52/52 [==============================] - 0s 4ms/step - loss: 0.2218 - mean_squared_error: 0.2218 - mean_absolute_error: 0.2501 - root_mean_squared_error: 0.4710 - val_loss: 0.5710 - val_mean_squared_error: 0.5710 - val_mean_absolute_error: 0.3395 - val_root_mean_squared_error: 0.7556
Epoch 27/100
52/52 [==============================] - 0s 5ms/step - loss: 0.2119 - mean_squared_error: 0.2119 - mean_absolute_error: 0.2501 - root_mean_squared_error: 0.4603 - val_loss: 0.8043 - val_mean_squared_error: 0.8043 - val_mean_absolute_error: 0.3558 - val_root_mean_squared_error: 0.8968
Epoch 28/100
52/52 [==============================] - 0s 5ms/step - loss: 0.1909 - mean_squared_error: 0.1909 - mean_absolute_error: 0.2316 - root_mean_squared_error: 0.4369 - val_loss: 0.4781 - val_mean_squared_error: 0.4781 - val_mean_absolute_error: 0.3253 - val_root_mean_squared_error: 0.6914
Epoch 29/100
52/52 [==============================] - 0s 7ms/step - loss: 0.1920 - mean_squared_error: 0.1920 - mean_absolute_error: 0.2265 - root_mean_squared_error: 0.4382 - val_loss: 0.8167 - val_mean_squared_error: 0.8167 - val_mean_absolute_error: 0.3502 - val_root_mean_squared_error: 0.9037
Epoch 30/100
52/52 [==============================] - 0s 7ms/step - loss: 0.1919 - mean_squared_error: 0.1919 - mean_absolute_error: 0.2471 - root_mean_squared_error: 0.4380 - val_loss: 0.9838 - val_mean_squared_error: 0.9838 - val_mean_absolute_error: 0.3747 - val_root_mean_squared_error: 0.9919
Epoch 31/100
52/52 [==============================] - 0s 7ms/step - loss: 0.1788 - mean_squared_error: 0.1788 - mean_absolute_error: 0.2310 - root_mean_squared_error: 0.4228 - val_loss: 0.6570 - val_mean_squared_error: 0.6570 - val_mean_absolute_error: 0.3193 - val_root_mean_squared_error: 0.8105
Epoch 32/100
52/52 [==============================] - 0s 8ms/step - loss: 0.1905 - mean_squared_error: 0.1905 - mean_absolute_error: 0.2258 - root_mean_squared_error: 0.4364 - val_loss: 0.5554 - val_mean_squared_error: 0.5554 - val_mean_absolute_error: 0.3351 - val_root_mean_squared_error: 0.7453
Epoch 33/100
52/52 [==============================] - 0s 7ms/step - loss: 0.2292 - mean_squared_error: 0.2292 - mean_absolute_error: 0.2228 - root_mean_squared_error: 0.4787 - val_loss: 0.7245 - val_mean_squared_error: 0.7245 - val_mean_absolute_error: 0.3310 - val_root_mean_squared_error: 0.8512
Epoch 34/100
52/52 [==============================] - 0s 8ms/step - loss: 0.1798 - mean_squared_error: 0.1798 - mean_absolute_error: 0.2206 - root_mean_squared_error: 0.4240 - val_loss: 0.6035 - val_mean_squared_error: 0.6035 - val_mean_absolute_error: 0.3155 - val_root_mean_squared_error: 0.7768
Epoch 35/100
52/52 [==============================] - 0s 7ms/step - loss: 0.1340 - mean_squared_error: 0.1340 - mean_absolute_error: 0.1998 - root_mean_squared_error: 0.3660 - val_loss: 0.7405 - val_mean_squared_error: 0.7405 - val_mean_absolute_error: 0.3336 - val_root_mean_squared_error: 0.8605
Epoch 36/100
52/52 [==============================] - 0s 6ms/step - loss: 0.1366 - mean_squared_error: 0.1366 - mean_absolute_error: 0.2091 - root_mean_squared_error: 0.3696 - val_loss: 0.6671 - val_mean_squared_error: 0.6671 - val_mean_absolute_error: 0.3723 - val_root_mean_squared_error: 0.8167
Epoch 37/100
52/52 [==============================] - 0s 5ms/step - loss: 0.1345 - mean_squared_error: 0.1345 - mean_absolute_error: 0.2027 - root_mean_squared_error: 0.3668 - val_loss: 0.7074 - val_mean_squared_error: 0.7074 - val_mean_absolute_error: 0.3433 - val_root_mean_squared_error: 0.8411
Epoch 38/100
52/52 [==============================] - 0s 5ms/step - loss: 0.1712 - mean_squared_error: 0.1712 - mean_absolute_error: 0.2251 - root_mean_squared_error: 0.4137 - val_loss: 0.6425 - val_mean_squared_error: 0.6425 - val_mean_absolute_error: 0.3394 - val_root_mean_squared_error: 0.8016
Epoch 39/100
52/52 [==============================] - 0s 5ms/step - loss: 0.1194 - mean_squared_error: 0.1194 - mean_absolute_error: 0.1930 - root_mean_squared_error: 0.3455 - val_loss: 0.8709 - val_mean_squared_error: 0.8709 - val_mean_absolute_error: 0.3490 - val_root_mean_squared_error: 0.9332
Epoch 40/100
52/52 [==============================] - 0s 5ms/step - loss: 0.1174 - mean_squared_error: 0.1174 - mean_absolute_error: 0.1963 - root_mean_squared_error: 0.3426 - val_loss: 0.7649 - val_mean_squared_error: 0.7649 - val_mean_absolute_error: 0.3447 - val_root_mean_squared_error: 0.8746
Epoch 41/100
52/52 [==============================] - 0s 5ms/step - loss: 0.1098 - mean_squared_error: 0.1098 - mean_absolute_error: 0.1890 - root_mean_squared_error: 0.3314 - val_loss: 0.4939 - val_mean_squared_error: 0.4939 - val_mean_absolute_error: 0.3386 - val_root_mean_squared_error: 0.7027
Epoch 42/100
52/52 [==============================] - 0s 5ms/step - loss: 0.1170 - mean_squared_error: 0.1170 - mean_absolute_error: 0.1937 - root_mean_squared_error: 0.3421 - val_loss: 0.6099 - val_mean_squared_error: 0.6099 - val_mean_absolute_error: 0.3443 - val_root_mean_squared_error: 0.7809
Epoch 43/100
52/52 [==============================] - 0s 5ms/step - loss: 0.1044 - mean_squared_error: 0.1044 - mean_absolute_error: 0.1908 - root_mean_squared_error: 0.3230 - val_loss: 0.5624 - val_mean_squared_error: 0.5624 - val_mean_absolute_error: 0.3201 - val_root_mean_squared_error: 0.7499
Epoch 44/100
52/52 [==============================] - 0s 4ms/step - loss: 0.0834 - mean_squared_error: 0.0834 - mean_absolute_error: 0.1671 - root_mean_squared_error: 0.2887 - val_loss: 0.7742 - val_mean_squared_error: 0.7742 - val_mean_absolute_error: 0.3441 - val_root_mean_squared_error: 0.8799
Epoch 45/100
52/52 [==============================] - 0s 5ms/step - loss: 0.1053 - mean_squared_error: 0.1053 - mean_absolute_error: 0.1825 - root_mean_squared_error: 0.3246 - val_loss: 0.5170 - val_mean_squared_error: 0.5170 - val_mean_absolute_error: 0.3251 - val_root_mean_squared_error: 0.7190
Epoch 46/100
52/52 [==============================] - 0s 5ms/step - loss: 0.0924 - mean_squared_error: 0.0924 - mean_absolute_error: 0.1704 - root_mean_squared_error: 0.3040 - val_loss: 0.7264 - val_mean_squared_error: 0.7264 - val_mean_absolute_error: 0.3289 - val_root_mean_squared_error: 0.8523
Epoch 47/100
52/52 [==============================] - 0s 4ms/step - loss: 0.0767 - mean_squared_error: 0.0767 - mean_absolute_error: 0.1597 - root_mean_squared_error: 0.2770 - val_loss: 1.1955 - val_mean_squared_error: 1.1955 - val_mean_absolute_error: 0.3667 - val_root_mean_squared_error: 1.0934
Epoch 48/100
52/52 [==============================] - 0s 5ms/step - loss: 0.1185 - mean_squared_error: 0.1185 - mean_absolute_error: 0.1869 - root_mean_squared_error: 0.3443 - val_loss: 0.7619 - val_mean_squared_error: 0.7619 - val_mean_absolute_error: 0.3700 - val_root_mean_squared_error: 0.8729
Epoch 49/100
52/52 [==============================] - 0s 5ms/step - loss: 0.1544 - mean_squared_error: 0.1544 - mean_absolute_error: 0.2047 - root_mean_squared_error: 0.3929 - val_loss: 0.9327 - val_mean_squared_error: 0.9327 - val_mean_absolute_error: 0.4291 - val_root_mean_squared_error: 0.9658
Epoch 50/100
52/52 [==============================] - 0s 6ms/step - loss: 0.1211 - mean_squared_error: 0.1211 - mean_absolute_error: 0.1897 - root_mean_squared_error: 0.3479 - val_loss: 0.5943 - val_mean_squared_error: 0.5943 - val_mean_absolute_error: 0.3254 - val_root_mean_squared_error: 0.7709
Epoch 51/100
52/52 [==============================] - 0s 5ms/step - loss: 0.0952 - mean_squared_error: 0.0952 - mean_absolute_error: 0.1693 - root_mean_squared_error: 0.3086 - val_loss: 0.7593 - val_mean_squared_error: 0.7593 - val_mean_absolute_error: 0.3749 - val_root_mean_squared_error: 0.8714
Epoch 52/100
52/52 [==============================] - 0s 5ms/step - loss: 0.0908 - mean_squared_error: 0.0908 - mean_absolute_error: 0.1715 - root_mean_squared_error: 0.3014 - val_loss: 0.7073 - val_mean_squared_error: 0.7073 - val_mean_absolute_error: 0.3321 - val_root_mean_squared_error: 0.8410
Epoch 53/100
52/52 [==============================] - 0s 5ms/step - loss: 0.0849 - mean_squared_error: 0.0849 - mean_absolute_error: 0.1601 - root_mean_squared_error: 0.2913 - val_loss: 0.6516 - val_mean_squared_error: 0.6516 - val_mean_absolute_error: 0.3354 - val_root_mean_squared_error: 0.8072
Epoch 54/100
52/52 [==============================] - 0s 5ms/step - loss: 0.0744 - mean_squared_error: 0.0744 - mean_absolute_error: 0.1594 - root_mean_squared_error: 0.2728 - val_loss: 0.5627 - val_mean_squared_error: 0.5627 - val_mean_absolute_error: 0.3115 - val_root_mean_squared_error: 0.7502
Epoch 55/100
52/52 [==============================] - 0s 5ms/step - loss: 0.0731 - mean_squared_error: 0.0731 - mean_absolute_error: 0.1571 - root_mean_squared_error: 0.2705 - val_loss: 0.6585 - val_mean_squared_error: 0.6585 - val_mean_absolute_error: 0.3398 - val_root_mean_squared_error: 0.8115
Epoch 56/100
52/52 [==============================] - 0s 5ms/step - loss: 0.0639 - mean_squared_error: 0.0639 - mean_absolute_error: 0.1502 - root_mean_squared_error: 0.2527 - val_loss: 0.7171 - val_mean_squared_error: 0.7171 - val_mean_absolute_error: 0.3349 - val_root_mean_squared_error: 0.8468
Epoch 57/100
52/52 [==============================] - 0s 5ms/step - loss: 0.0616 - mean_squared_error: 0.0616 - mean_absolute_error: 0.1462 - root_mean_squared_error: 0.2481 - val_loss: 0.7948 - val_mean_squared_error: 0.7948 - val_mean_absolute_error: 0.3468 - val_root_mean_squared_error: 0.8915
Epoch 58/100
52/52 [==============================] - 0s 4ms/step - loss: 0.0603 - mean_squared_error: 0.0603 - mean_absolute_error: 0.1426 - root_mean_squared_error: 0.2457 - val_loss: 0.7328 - val_mean_squared_error: 0.7328 - val_mean_absolute_error: 0.3372 - val_root_mean_squared_error: 0.8560
Epoch 59/100
52/52 [==============================] - 0s 5ms/step - loss: 0.0640 - mean_squared_error: 0.0640 - mean_absolute_error: 0.1507 - root_mean_squared_error: 0.2529 - val_loss: 0.7255 - val_mean_squared_error: 0.7255 - val_mean_absolute_error: 0.3624 - val_root_mean_squared_error: 0.8518
Epoch 60/100
52/52 [==============================] - 0s 5ms/step - loss: 0.0569 - mean_squared_error: 0.0569 - mean_absolute_error: 0.1428 - root_mean_squared_error: 0.2385 - val_loss: 0.7010 - val_mean_squared_error: 0.7010 - val_mean_absolute_error: 0.3221 - val_root_mean_squared_error: 0.8373
Epoch 61/100
52/52 [==============================] - 0s 4ms/step - loss: 0.0515 - mean_squared_error: 0.0515 - mean_absolute_error: 0.1353 - root_mean_squared_error: 0.2270 - val_loss: 0.8075 - val_mean_squared_error: 0.8075 - val_mean_absolute_error: 0.3401 - val_root_mean_squared_error: 0.8986
Epoch 62/100
52/52 [==============================] - 0s 5ms/step - loss: 0.0507 - mean_squared_error: 0.0507 - mean_absolute_error: 0.1365 - root_mean_squared_error: 0.2252 - val_loss: 0.6193 - val_mean_squared_error: 0.6193 - val_mean_absolute_error: 0.3334 - val_root_mean_squared_error: 0.7870
Epoch 63/100
52/52 [==============================] - 0s 4ms/step - loss: 0.0572 - mean_squared_error: 0.0572 - mean_absolute_error: 0.1401 - root_mean_squared_error: 0.2391 - val_loss: 0.7116 - val_mean_squared_error: 0.7116 - val_mean_absolute_error: 0.3357 - val_root_mean_squared_error: 0.8436
Epoch 64/100
52/52 [==============================] - 0s 6ms/step - loss: 0.0657 - mean_squared_error: 0.0657 - mean_absolute_error: 0.1455 - root_mean_squared_error: 0.2563 - val_loss: 0.7330 - val_mean_squared_error: 0.7330 - val_mean_absolute_error: 0.3249 - val_root_mean_squared_error: 0.8561
Epoch 65/100
52/52 [==============================] - 0s 5ms/step - loss: 0.0792 - mean_squared_error: 0.0792 - mean_absolute_error: 0.1483 - root_mean_squared_error: 0.2814 - val_loss: 0.6011 - val_mean_squared_error: 0.6011 - val_mean_absolute_error: 0.3287 - val_root_mean_squared_error: 0.7753
Epoch 66/100
52/52 [==============================] - 0s 5ms/step - loss: 0.0915 - mean_squared_error: 0.0915 - mean_absolute_error: 0.1701 - root_mean_squared_error: 0.3025 - val_loss: 0.7626 - val_mean_squared_error: 0.7626 - val_mean_absolute_error: 0.3416 - val_root_mean_squared_error: 0.8733
Epoch 67/100
52/52 [==============================] - 0s 5ms/step - loss: 0.0665 - mean_squared_error: 0.0665 - mean_absolute_error: 0.1496 - root_mean_squared_error: 0.2579 - val_loss: 0.6970 - val_mean_squared_error: 0.6970 - val_mean_absolute_error: 0.3266 - val_root_mean_squared_error: 0.8349
Epoch 68/100

In [ ]:
y_train.iloc[0:10]

266     0.950
1133    1.251
1823    0.660
1370    1.650
67      0.190
1009    0.275
1763    0.450
1969    5.200
1313    0.650
1537    0.390
Name: Price, dtype: float64

In [ ]:
# X_train.iloc[0:2]
pred2 = model.predict(X_train.iloc[0:10])
print(pred2)

1/1 [==============================] - 0s 22ms/step
[[1.0142617 ]
 [1.3137816 ]
 [0.74083906]
 [1.8813952 ]
 [0.19036427]
 [0.29510844]
 [0.4601033 ]
 [6.4551854 ]
 [0.5922934 ]
 [0.3720576 ]]

In [ ]:
# Step 7: Evaluate the Model
loss = model.evaluate(X_test, y_test)
print(f"Mean Squared Error: {loss}")

13/13 [==============================] - 0s 2ms/step - loss: 0.7548 - mean_squared_error: 0.7548 - mean_absolute_error: 0.3275 - root_mean_squared_error: 0.8688
Mean Squared Error: [0.7548460960388184, 0.7548460960388184, 0.32745563983917236, 0.8688188195228577]